# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c73aa3473dd317305ea08feda83295c9d4c9fc779b6cd9de6f206295793465a0e4338fc8d8ecca010748fe938ca63a2dca86d04ac044133ed6c4b9faae53cc50

test:
  secret_key_base: e1966430dc6b775165396700a19030b286b89df7bce9a7d3570237b2144f69ba6d43c27d8e0bb581abd93c0903ed209def799bdf691203e2b95ce67437dcd76f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
